### ISSUE TITLE
Unable to parse expression in Flutter

### ISSUE THREAD

**Issue by gfh21cn** [appsup-dart/expressions#1]
Code:
Expression expression = Expression.parse("V1>50");

This code works fine in dart programs, but when I use it in Flutter, an exception occurs

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk (31.1MB).
I/FlutterActivityDelegate( 3743): onResume setting current activity to this
E/flutter ( 3743): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 3743): 'package:expressions/src/parser.dart': error: line 12 pos 23: file:///C:/Users/lenovo/AppData/Roaming/Pub/Cache/hosted/pub.flutter-io.cn/expressions-0.1.0/lib/src/parser.dart:12:23: Error: A value of type 'typedparser::Parser<expressions.core::UnaryExpression>' can't be assigned to a variable of type 'typedparser::Parser<expressions.core::Literal>'.
E/flutter ( 3743): Try changing the type of the left hand side, or casting the right hand side to 'typedparser::Parser<expressions.core::Literal>'.
E/flutter ( 3743):     token.set(literal|unaryExpression|variable); // ignore: argument_type_not_assignable
E/flutter ( 3743):                       ^
E/flutter ( 3743):     token.set(literal|unaryExpression|variable); // ignore: argument_type_not_assignable
E/flutter ( 3743):                       ^
E/flutter ( 3743):
E/flutter ( 3743): #0      Expression._parser (package:expressions/src/expressions.dart:27:47)
E/flutter ( 3743): #1      Expression._parser (package:expressions/src/expressions.dart:27:33)
E/flutter ( 3743): #2      Expression.parse (package:expressions/src/expressions.dart:30:16)
E/flutter ( 3743): #3      main (file:///E:/MyWork/livebuilding/lib/main.dart:14:38)
E/flutter ( 3743): #4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
E/flutter ( 3743): #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

![image](https://user-images.githubusercontent.com/18669068/38776777-2ccc99c8-40cf-11e8-95ec-7984321d1805.png)

test environment

![image](https://user-images.githubusercontent.com/18669068/38776803-9c76acc8-40cf-11e8-87e3-19fca7cce26b.png)

**Comment by rbellens** [comment]
Thanks for the feedback. 
The issue should be fixed in new release. Please update your dependency to `^0.1.1`. Can you confirm that it works now?

**Comment by gfh21cn** [comment]
yes,it's ok,tks

**Comment by rbellens** [comment]
great
