### ISSUE TITLE
Parse string methods.

### ISSUE THREAD

**Issue by danielweil** [appsup-dart/expressions#10]
Is there any way to parse string methods?

Everytime i try to use string methods that do not come from variables I get: 

"Unhandled exception:
end of input expected at x:y"

Thanks for the excelent package.
Daniel

**Comment by apgapg** [comment]
For using strings methods you need to override callexpression and provide the funciton manually. For example parseAsString(24)

**Comment by danielweil** [comment]
Yes, that I am aware. My problem is I want the parser to be able to handle string directly in the expression. I that possible?

Instead of image 1, do it as image 2.

![image](https://user-images.githubusercontent.com/44274213/94995913-c3d9a580-0577-11eb-926d-61cbd71c053c.png)

![image](https://user-images.githubusercontent.com/44274213/94995925-d2c05800-0577-11eb-81c8-c14d047e1b11.png)

**Comment by apgapg** [comment]
@danielweil '2'.days doesnt make any sense. See the expression parsing is failing at 24 char

**Comment by danielweil** [comment]
It is a method I created. If it was any other in dart language, is there any way that it would work?

For instance,

"2 ".trim()

What about the  parseAsString(24) you told me above, can you be a bit more clear? Do I have to implement this in a custom class? Like "x.parseAsString(24)", {'x': CustomClass}?

**Comment by apgapg** [comment]
```
class ResponseEvaluator extends ExpressionEvaluator {
  const ResponseEvaluator();

  @override
  dynamic evalCallExpression(
    CallExpression expression,
    Map<String, dynamic> context,
  ) {
    if (expression.callee is Variable &&
        (expression.callee as Variable).identifier.name == "roundOff") {
      final arguments =
          expression.arguments.map((e) => eval(e, context)).toList();
      return Function.apply(roundOff, arguments);
    } else if (expression.callee is Variable &&
        (expression.callee as Variable).identifier.name == "subtractDates") {
      final arguments =
          expression.arguments.map((e) => eval(e, context)).toList();
      return Function.apply(subtractDates, arguments);
    } else if (expression.callee is Variable &&
        (expression.callee as Variable).identifier.name == "toString") {
      final arguments =
          expression.arguments.map((e) => eval(e, context)).toList();
      return Function.apply(convertToString, arguments);
    } else if (expression.callee is Variable &&
        (expression.callee as Variable).identifier.name == "toDouble") {
      final arguments =
          expression.arguments.map((e) => eval(e, context)).toList();
      return Function.apply(convertToDouble, arguments);
    }
    return super.evalCallExpression(expression, context);
  }
}
```

@danielweil  See how i created custom methods for utilising string methods. Note you cant access string methods directly here because. expression wont evaluate.

to use above methods `toString(23)`

**Comment by danielweil** [comment]
Thanks! That cleared all my doubts!
