### ISSUE TITLE
? in expression

### ISSUE THREAD

**Issue by danielweil** [appsup-dart/expressions#11]
Hello, 

I asked a question about using methods in strings in the parser, and I was told to overwrite evalCallExpressions.

Now I am trying to evalutate methods with '?' in the end, and am having trouble to parse. 
Another question is about ternary operators. Do you see any way to parse them?

Thanks for the help!
Daniel

**Comment by danielweil** [comment]
I tried escaping but had no success.

**Comment by apgapg** [comment]
const exp = "1==2? 'value1' : 'value2' '"

The result would be exp=' value2'

**Comment by danielweil** [comment]
That was just part of my question. My main doubt was about using ? in method names. The parser gives me back an error,
![image](https://user-images.githubusercontent.com/44274213/95020761-762a6f00-0643-11eb-8086-d283a0ea3d19.png)

My doubt about the ternary operator continues. I tried exactly what you told me but still gets an error.

![image](https://user-images.githubusercontent.com/44274213/95020748-5bf09100-0643-11eb-9f7b-66b0b57ffebd.png)

**Comment by apgapg** [comment]
Okay let me check once.

**Comment by danielweil** [comment]
Any updates?

**Comment by apgapg** [comment]
```
    test('? ternary operator', () {
      const expression = "1==2?'value1':'value2'";
      final result = evaluateSyncExpression(
        expression: expression,
        map: <String, dynamic>{},
      );
      expect(result, 'value2');
    });
```

This works in my case

**Comment by danielweil** [comment]
Can you imagine why is it not working here? I am using the same example as you are.

**Comment by apgapg** [comment]
As per the logs its failing at `evalConditionalExpression`.
Can you show your MyEvaluator() class code?

**Comment by danielweil** [comment]
I do not have this method implemented. (evalConditionalExpression). Should I?

**Comment by danielweil** [comment]
Just figured it out. When I was returning super's evalBinaryExpression, I was returning a function instead of a bool. Thanks for your time!
