### ISSUE TITLE
Parsing RegEx as a variable in an Expression.

### ISSUE THREAD

**Issue by TheOlajos** [appsup-dart/expressions#13]
I'm looking to parse out a string containing regex to an expression:

 Expression expression = Expression.parse(s);

This fails with end of input expected if the RegEx contains \ or ' and there seems to be no way to escape these characters.

**Comment by apgapg** [comment]
Can you please share a sample string?

**Comment by isaacolajos** [comment]
eval(regex('{inp1}','[a-z0-9!#$%&\'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&\'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?', 'has'))

This is the incoming string, if I replate the second parameter (the RegEx string) with a simple regex not containing \ or ' it works without issue. 

ie: eval(regex('{inp1}','[a-z0-9])?', 'has'))

**Comment by apgapg** [comment]
You can try using double quotes instead of a single one in the second parameter. Can you please share sample flutter project?

**Comment by rbellens** [comment]
The \\ was not parsed. This is now fixed in v0.2.5.

**Comment by TheOlajos** [comment]
Awesome thank you.
