### ISSUE TITLE
Power function

### ISSUE THREAD

**Issue by alan-qbasic** [appsup-dart/expressions#14]
The power function "^" doesn't return the correct answer.

Also, this is what I get when using a double.
Class 'double' has no instance method '^'

How do I use the power function?

**Comment by apgapg** [comment]
You cant use ^ for power as it is bitwise operator. You have to override Eval member exp method and create a function like pow(2,4) which return 2^4

**Comment by alan-qbasic** [comment]
Thank you. It worked!!!!!
