### ISSUE TITLE
Leading and trailing spaces throw errors with Expression.parse

### ISSUE THREAD

**Issue by oodavid** [appsup-dart/expressions#19]
Firstly, we *love* this package. It's been great for our app!

Issue is simple, if the expression has leading or trailing spaces, the parser throws an error:

```dart
import 'package:expressions/expressions.dart';
void main() {
  // Throws
  Expression.parse("myVar == false ");
  // Throws
  Expression.parse(" myVar == false ");
}
```

We simply run `trim` on our expressions before parsing, but thought it worth creating an issue.

**Comment by dsyrstad** [comment]
We also have an issue with whitespace, although it's a different case:

```dart
import 'package:expressions/expressions.dart';

void main() {
  const evaluator = ExpressionEvaluator();

  const expression = 'func()';    // 'func( )'; fails
  final result = evaluator.eval(Expression.parse(expression), {
    'func': () => 42,
  });

  print('result=$result');
}
```

This program will print `result=42`. However if I put a space in between the `()` of the function call, like so:

```dart
  const expression = 'func( )';
```

`Expression.parse()` throws the error: `end of input expected at 1:5`.

**Comment by rbellens** [comment]
fixed now
