### ISSUE TITLE
showing exponential number instead full number. please show full number.

### ISSUE THREAD

**Issue by vishnuvardhankota** [appsup-dart/expressions#25]
Read the below code and understand for large number calculation of multiplications.

// Multiplies str1 and str2, and prints result.
multiply(num1, num2) {
  var len1 = num1.length;
  var len2 = num2.length;
  if (len1 == 0 || len2 == 0) {
    return "0";
  }

  // will keep the result number in vector
  // in reverse order
  var result = List.filled(len1 + len2, 0);

  // Below two indexes are used to
  // find positions in result.
  var i_n1 = 0;
  var i_n2 = 0;

  // Go from right to left in num1
  for (var i = len1 - 1; i > -1; i--) {
    var carry = 0;
    final n1 = (num1[i]).codeUnits[0] - 48;

    // To shift position to left after every
    // multiplication of a digit in num2
    i_n2 = 0;

    // Go from right to left in num2
    for (var j = len2 - 1; j > -1; j--) {
      // Take current digit of second number
      final n2 = (num2[j]).codeUnits[0] - 48;

      // Multiply with current digit of first number
      // and add result to previously stored result
      // at current position.
      final summ = n1 * n2 + result[i_n1 + i_n2] + carry;

      // Carry for next iteration
      carry = (summ / 10).floor();

      // Store result
      result[i_n1 + i_n2] = summ % 10;

      i_n2 += 1;
    }

    // store carry in next cell
    if (carry > 0) {
      result[i_n1 + i_n2] += carry;
    }
    // To shift position to left after every
    // multiplication of a digit in num1.
    i_n1 += 1;

    // print(result)
  }
  // ignore '0's from the right
  var i = result.length - 1;
  while (i >= 0 && result[i] == 0) {
    i -= 1;
  }

  // If all were '0's - means either both or
  // one of num1 or num2 were '0'
  if (i == -1) {
    return "0";
  }

  // generate the result string
  var s = "";
  while (i >= 0) {
    s += String.fromCharCode(result[i] + 48);
    i -= 1;
  }

  return s;
}

void main() {
  // Driver code
  var str1 = "1235421415454545454545454544";
  var str2 = "1714546546546545454544548544544545";

  if ((str1[0] == '-' || str2[0] == '-') &&
      (str1[0] != '-' || str2[0] != '-')) {
    print("-");
  }

  if (str1[0] == '-' && str2[0] != '-') {
    str1.substring(1);
  } else if (str1[0] != '-' && str2[0] == '-') {
    str2.substring(1);
  } else if (str1[0] == '-' && str2[0] == '-') {
    str1.substring(1);
    str2.substring(1);
  }
  print(multiply(str1, str2));
}

**Comment by rbellens** [comment]
Has this anything to do with this package?
