### ISSUE TITLE
Concat function

### ISSUE THREAD

**Issue by willwees** [appsup-dart/expressions#27]
I have an expression something like this.

```dart
var context = <String, dynamic>{
    a: '10',
    b: 'apples'
};

String expression = "(a=='10' ? 'ten' : 'other').concat('_').concat(b)";  // Expected output: 'ten_apples'

```

Is there any example how to do this?

Thanks for the awesome package!

**Comment by rbellens** [comment]
There are two options. The default `ExpressionEvaluator` does not handle member expressions, but you can give an argument `memberAccessors` to the constructor. E.g.:

```dart
var evaluator = ExpressionEvaluator(
  memberAccessors: [MemberAccessor<String>({
    'concat': (left)=>(right)=>'$left$right'
  })]);
````

The other option is to use plain functions iso member methods. E.g.:

```dart
evaluator.eval(expression, {
  'a': '10',
  'b': 'apples',
  'concat': (left,right)=>'$left$right',
});
```
