### ISSUE TITLE
Update pubspec.yaml "petitparser" to 3.0.0

### ISSUE THREAD

**Issue by alex-misch** [appsup-dart/expressions#5]
Hello.
Thanks for your amazing package!
I've got an issue when using your package together with any package that requires [xml 3.7.0](https://pub.dev/packages/xml/versions/3.7.0) . For example, any of [aws sdk packages](https://github.com/agilord/aws_client/tree/master/generated) . 
To reproduce it, add in pubspec.yaml following dependencies:
```
dependencies:
  expressions: ^0.1.2
  aws_sns_api: ^0.0.2
```
and try to run `flutter pub get`. You will get an error:
```
Because every version of aws_sns_api depends on shared_aws_api ^0.1.0 which depends on xml ^3.7.0, every version of aws_sns_api requires xml ^3.7.0.
And because xml >=3.7.0 depends on petitparser ^3.0.0, every version of aws_sns_api requires petitparser ^3.0.0.


And because expressions 0.1.2 depends on petitparser ^2.0.0 and no versions of expressions match >0.1.2 <0.2.0, aws_sns_api is incompatible with expressions ^0.1.2.
```
Simplified depencency tree: 
| _ `shared_aws_api  ^0.1.0`
| ___`xml ^3.7.0`
| _____`petitparser ^3.0.0`

| _`expressions ^0.1.2`
| ___`petitparser ^2.0.0`

2.0.0 not match with 3.0.0

**Comment by rbellens** [comment]
Hi @alex-misch ,
should be fixed in latest version (0.1.3)
