### ISSUE TITLE
Add Exponent operator

### ISSUE THREAD

**Issue by malown** [appsup-dart/expressions#7]
The exponent operator is very commonly used in geometry and algebra. At the moment one could add the function pow to the context when the expression is evaluated, however that makes the expression less readable.

I noticed that Dart itself doesn't support the ** operator like most languages, but i'd suggest using it in this case.

**Comment by apgapg** [comment]
Its already there i guess
` case '^':
        return left ^ right();`

Try a test case of 2^2 and see if it evaluates correctly

**Comment by malown** [comment]
That's  the bitwise XOR operator
https://en.wikipedia.org/wiki/Bitwise_operations_in_C#Bitwise_XOR_^

**Comment by malown** [comment]
That will interfere with the bitwise XOR mentioned above. Also, you didn't set the precedence for the operator so the expression 5 * 3^2 gets evaluated as (5 * 3)^2

Check out my repo for a solution. I Used the ° sign as the exponent operator as i couldn't get ** to get parsed properly

https://github.com/malown/expressions

**Comment by apgapg** [comment]
You can simply define a callMemberExpression like 'pow(2,2)'

**Comment by malown** [comment]
For my usecase i need the expression to be easily readable by humans without using regex

**Comment by Throvn** [comment]
Does someone have a solution for this?
Unfortunately @malown took all of their repositories down
and I have no clue on how to extend the code snippet above to make it work properly :(
