### ISSUE TITLE
Escaping  apostrophe in String

### ISSUE THREAD

**Issue by fafriat** [appsup-dart/expressions#8]
Hi,

I am trying to  escape apostrophe in String but without success.
I tried preceding it with backlash or doubling but it is not working.

example: 
Expression.parse("json.name == 'A\\'B'");
is causing  failure: end of input expected at ...

is it possible to include apostrophe in String ?

**Comment by rbellens** [comment]
You should make sure that the \ char is inside the string that is passed to the parser. In your code it is not. So, either use a double slash or use a raw string:

```dart
Expression.parse("json.name == 'A\\'B'");
Expression.parse(r"json.name == 'A\'B'");
```
